#! /bin/sh

# turn on echo
set -x

# cleanup should not be necessary
# however, in some cases strange results are found if you do not start clean
rm -rf autom4te.cache
rm -f aclocal.m4 Makefile.in 
rm -f configure config.* depcomp install-sh missing mk*

# run autotool commands
aclocal 
automake --add-missing --copy
autoconf 

#run autotool commands in each subdirectory
for pkg in `ls`
do
  if [ -e $pkg/configure.ac ] 
  then
     cd $pkg
     ./bootstrap
     cd ..
  fi
done


# ready to make a source code distribution tarball
