#!/bin/sh

# use this in the build directory, NOT in the source code tree

usage()
{
    cat  <<EOF
Usage: buildLibraries <CLHEP source code directory> <build directory> <install directory>
All three directories must be specified and must be unique.
Use the full path for all directory names.

For example: buildLibraries /fullpath/CLHEP /fullpath/build /fullpath/inst

EOF

    exit $1
}

if test $# -lt 3; then
    usage 1
fi

if [ ! -d $1 ] 
then
  echo "source directory $1 does not exist"
  exit 2
fi

if [ ! -d $2 ] 
then
  echo "build directory $2 does not exist"
  exit 3
fi

if [ ! -d $3 ] 
then
  echo "install directory $3 does not exist"
  exit 4
fi

cd $2

$1/configure --prefix=$3 --includedir=$3/include/CLHEP > log.configure.$$ 2>&1

# create temporary include subdirectory for each package
for pkg in `ls`
do
  if [ -e $pkg/Makefile ] 
  then
     cd $pkg
     if [ ! -d CLHEP ] 
     then
       mkdir CLHEP
       for pkg in `ls $1`
       do
	 if [ -d $1/$pkg/$pkg ] 
	 then
	    ln -s $1/$pkg/$pkg CLHEP/$pkg
	 fi
       done
     fi
     cd ..
  fi
done

make > log.make.$$ 2>&1
make check > log.check.$$ 2>&1
make install > log.install.$$ 2>&1

exit 0
