#!/bin/sh

# make source code tarballs 
# This script assumes that the bootstrap script has already been run successfully.


# makeSourceDist <path to CLHEP source> <tarball directory>
#  $1 is the path above the CLHEP source code direcotry
#  e.g. for /pathto/CLHEP, $1 is /pathto

if [ ! -d $1/CLHEP ] 
then
    echo "$1/CLHEP does not exist"
    exit 1
fi

if [ ! -d $2 ] 
then
    echo "$2 does not exist"
    exit 1
fi

##set -x

# make sure we have the full path
thisdir=`pwd`
cd $1; thatdir=`pwd`
cd $thisdir
cd $2; tardir=`pwd`

cd $thatdir;
tar -cf $tardir/src-CLHEP.tar CLHEP

for pkg in `ls $thatdir/CLHEP`
do
    if [ -e $thatdir/CLHEP/$pkg/configure.in ] 
    then
        cd $thatdir;
        tar -cf $tardir/src-CLHEP-$pkg.tar CLHEP/$pkg
    fi
done
