#!/bin/sh

# use this in the build directory, NOT in the source code tree

usage()
{
    cat  <<EOF
Usage: buildLibraries <CLHEP source code directory> <build directory> <install directory>
All three directories must be specified and must be unique.
Use the full path for all directory names.

For example: buildLibraries /fullpath/CLHEP /fullpath/build /fullpath/inst

EOF

    exit $1
}

if test $# -lt 3; then
    usage 1
fi

if [ ! -d $1 ] 
then
  echo "source directory $1 does not exist"
  exit 2
fi

if [ ! -d $2 ] 
then
  echo "build directory $2 does not exist"
  exit 3
fi

if [ ! -d $3 ] 
then
  echo "install directory $3 does not exist"
  exit 4
fi

# create subdirectory in build area for each package
if [ ! -d $2/GenericFunctions ] 
then
  mkdir $2/GenericFunctions
fi
cd $2/GenericFunctions

# create temporary include subdirectory
if [ ! -d CLHEP ] 
then
  mkdir CLHEP
  for pkg in `ls $1`
  do
    if [ -d $1/$pkg/$pkg ] 
    then
       ln -s $1/$pkg/$pkg CLHEP/$pkg
    fi
  done
fi

$1/GenericFunctions/configure --prefix=$3 --includedir=$3/include/CLHEP --datadir=$3/doc > log.configure.$$ 2>&1

make > log.make.$$ 2>&1
if [ -d test ] 
then
  make check > log.check.$$ 2>&1
fi
make install > log.install.$$ 2>&1

exit 0
