#!/bin/sh

# create a temporary CLHEP include subdirectory
# use this in the build directory, NOT in the source code tree

# makeCLHEP <top of source>
#  $1 is the CLHEP (or equivalent) source code direcotry
#  e.g. for /path/somedir/Vector, $1 is /path/somedir

if [ $# -lt 1 ] 
then
   echo "you must supply the path to the top of the source code directory"
   exit 1
fi

# create temporary include subdirectory
# if this directory already exists, we assume that everything is correct
if [ ! -d CLHEP ] 
then
  # make sure we have the full path
  thisdir=`pwd`
  cd $1; thatdir=`pwd`
  cd $thisdir
  # make the directory and links
  mkdir CLHEP
  for pkg in `ls $thatdir`
  do
    if [ -d $thatdir/$pkg/$pkg ] 
    then
       ln -s $thatdir/$pkg/$pkg CLHEP/$pkg
    fi
  done
  # check $CLHEP_DIR for extra packages
  if [ -n $CLHEP_DIR ] && [ -d $CLHEP_DIR/CLHEP ]
  then
     for cpkg in `ls $CLHEP_DIR/CLHEP`
     do
         if [ -d $CLHEP_DIR/CLHEP/$cpkg/$cpkg ] && [ ! -L CLHEP/$cpkg ]
	 then
	    echo "link $CLHEP_DIR/CLHEP/$cpkg/$cpkg CLHEP/$cpkg"
	    ln -s  $CLHEP_DIR/CLHEP/$cpkg/$cpkg CLHEP/$cpkg
	 fi
     done
  fi
fi

